// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK3GRQoCkgszuTQsvzwRNtfu5KG1rGx8c',
    appId: '1:322505600911:web:70475e2ea0b0b93542e5fa',
    messagingSenderId: '322505600911',
    projectId: 'flood-sense-cf40a',
    authDomain: 'flood-sense-cf40a.firebaseapp.com',
    storageBucket: 'flood-sense-cf40a.firebasestorage.app',
    measurementId: 'G-YMQQP8EV7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANY8wCweFPQszYOjW7NKjXaXL9DU8sA40',
    appId: '1:322505600911:android:240fe7be3ae84c5e42e5fa',
    messagingSenderId: '322505600911',
    projectId: 'flood-sense-cf40a',
    storageBucket: 'flood-sense-cf40a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwoTM1joypZ0VSVn3zj24fcq7xxMz-96I',
    appId: '1:322505600911:ios:473c278cbcc5dc4042e5fa',
    messagingSenderId: '322505600911',
    projectId: 'flood-sense-cf40a',
    storageBucket: 'flood-sense-cf40a.firebasestorage.app',
    iosBundleId: 'com.example.floodsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwoTM1joypZ0VSVn3zj24fcq7xxMz-96I',
    appId: '1:322505600911:ios:473c278cbcc5dc4042e5fa',
    messagingSenderId: '322505600911',
    projectId: 'flood-sense-cf40a',
    storageBucket: 'flood-sense-cf40a.firebasestorage.app',
    iosBundleId: 'com.example.floodsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK3GRQoCkgszuTQsvzwRNtfu5KG1rGx8c',
    appId: '1:322505600911:web:8cbb8cbbd001c56842e5fa',
    messagingSenderId: '322505600911',
    projectId: 'flood-sense-cf40a',
    authDomain: 'flood-sense-cf40a.firebaseapp.com',
    storageBucket: 'flood-sense-cf40a.firebasestorage.app',
    measurementId: 'G-QC8W2LSTKF',
  );
}
